apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "mondoo-operator.labels" . | nindent 4 }}
  name: controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    {{- include "mondoo-operator.selectorLabels" . | nindent 4 }}
