# permissions for end users to edit mondooclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mondooclient-editor-role
rules:
- apiGroups:
  - k8s.mondoo.com
  resources:
  - mondooclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.mondoo.com
  resources:
  - mondooclients/status
  verbs:
  - get
