---
apiVersion: batch/v1
kind: Job
metadata:
  name: mondoo-job
spec:
  template:
    spec:
      containers:
        - name: mondoo-agent
          image: docker.io/mondoolabs/mondoo:latest
          command:
            [
              "mondoo",
              "scan",
              "--inventory",
              "/etc/opt/mondoo/inventory.yml",
              "--config",
              "/etc/opt/mondoo/mondoo.yml",
              "--exit-0-on-success",
            ]
          volumeMounts:
            - name: root
              mountPath: /mnt/host/
              readOnly: true
            - name: config
              mountPath: /etc/opt/
              readOnly: true
          env:
            - name: DEBUG
              value: "false"
            - name: MONDOO_PROCFS
              value: "on"
      restartPolicy: Never
      volumes:
        - name: root
          hostPath:
            path: "/"
        - name: config
          projected:
            sources:
              - secret:
                  name: mondoo-credentials
                  items:
                    - key: config
                      path: mondoo/mondoo.yml
              - configMap:
                  name: mondoo-inventory
                  items:
                    - key: inventory
                      path: mondoo/inventory.yml
