version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    ignore:
      # These dependencies are inherited from our usage of OperatorSDK
      # and they get updated as we follow OperatorSDK's releases
      - dependency-name: sigs.k8s.io/controller-runtime
      - dependency-name: k8s.io/apimachinery
      - dependency-name: k8s.io/client-go
      - dependency-name: k8s.io/api
