# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

# This service is used for allowing direct http scraping by Prometheus
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mondoo-operator
  name: controller-manager-metrics-service
  namespace: mondoo-operator
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: mondoo-operator
