apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-manager
  namespace: system
  labels:
    control-plane: webhook-manager
spec:
  selector:
    matchLabels:
      control-plane: webhook-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: webhook-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /webhook
        image: controller:latest
        imagePullPolicy: IfNotPresent
        name: webhook
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      #serviceAccountName: default
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
