apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mondoo-operator
namePrefix: mondoo-operator-
resources:
- manifests.yaml
images:
- name: controller
  newName: ghcr.io/mondoohq/mondoo-operator
  newTag: sha256-0221c743e368dbb651f097beaf0a21bcb36acd3b.sig
