---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- name: policy.k8s.mondoo.com
  # The default is 10s but on slow clusters we may take longer
  timeout: 20s