# permissions for end users to view mondoooperatorconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mondoooperatorconfig-viewer-role
rules:
- apiGroups:
  - k8s.mondoo.com
  resources:
  - mondoooperatorconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.mondoo.com
  resources:
  - mondoooperatorconfigs/status
  verbs:
  - get
