# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.mondoo.com
  resources:
  - mondooauditconfigs
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - k8s.mondoo.com
  resources:
  - mondooauditconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.mondoo.com
  resources:
  - mondooauditconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.mondoo.com
  resources:
  - mondoooperatorconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.mondoo.com
  resources:
  - mondoooperatorconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.mondoo.com
  resources:
  - mondoooperatorconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
