apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mondoo-operator.fullname" . }}-manager-role
  labels:
  {{- include "mondoo-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.mondoo.com
  resources:
  - mondooauditconfigs
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - k8s.mondoo.com
  resources:
  - mondooauditconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.mondoo.com
  resources:
  - mondooauditconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.mondoo.com
  resources:
  - mondoooperatorconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.mondoo.com
  resources:
  - mondoooperatorconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.mondoo.com
  resources:
  - mondoooperatorconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mondoo-operator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "mondoo-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "mondoo-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "mondoo-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'