# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

apiVersion: v1
kind: Service
metadata:
  name: {{ include "mondoo-operator.fullname" . }}-controller-manager-metrics-service
  labels:
  {{- include "mondoo-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
  {{- include "mondoo-operator.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}