apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Full Lifecycle
    categories: Security
    certified: "false"
    containerImage: ghcr.io/mondoohq/mondoo-operator:v0.0.10
    description: Mondoo is a cloud security platform for infrastructure developers.
      Using Mondoo, your team will get automated risk assessment and real-time insights
      into all of your business critical infrastructure, across all of your infrastructure
      platforms.
    repository: https://github.com/mondoohq/mondoo-operator
    support: Mondoo
  name: mondoo-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MondooAuditConfig is the Schema for the mondooauditconfigs API
      displayName: Mondoo Audit Config
      kind: MondooAuditConfig
      name: mondooauditconfigs.k8s.mondoo.com
      version: v1alpha1
  description: A Kubernetes Operator for creating and managing Mondoo controller instances.
  displayName: mondoo-operator
  icon:
  - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iMzAwcHgi
      IGhlaWdodD0iMzAwcHgiIHZpZXdCb3g9IjAgMCAzMDAgMzAwIiB2ZXJzaW9uPSIxLjEiIHhtbG5z
      PSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMu
      b3JnLzE5OTkveGxpbmsiPgogICAgPHRpdGxlPkFydGJvYXJkPC90aXRsZT4KICAgIDxnIGlkPSJB
      cnRib2FyZCIgc3Ryb2tlPSJub25lIiBzdHJva2Utd2lkdGg9IjEiIGZpbGw9Im5vbmUiIGZpbGwt
      cnVsZT0iZXZlbm9kZCI+CiAgICAgICAgPHBhdGggZD0iTTI0OCwyMjUgTDIxNC40OTU3MjYsMjI1
      IEwyMDIuNzE1MTkyLDEzMy4zNTI0NTkgTDE2My4wNzc0NzQsMjA4LjI1NDA5OCBMMTM3LjM4MTg1
      OCwyMDguMjU0MDk4IEw5Ny4yODQ4MDg0LDEzMy4zNTI0NTkgTDg1LjUwNDI3MzUsMjI1IEw1Miwy
      MjUgTDcyLjA0ODUyNSw3NSBMODguODI3NjgxMyw3NSBDOTIuMTMyMTc1NCw3NSA5NS4zNjkxMjA1
      LDc1Ljg0ODM2MDcgOTguMTU3NTQwNyw3Ny40NjE0NzU0IEMxMDAuOTQ4NjYzLDc5LjA3MjEzMTEg
      MTAzLjE3NTA3Niw4MS4zNzM3NzA1IDEwNC41ODAwOTQsODQuMDk4MzYwNyBMMTUwLjA1NDAzOSwx
      NzQuMDk4MzYxIEwxOTUuMTIyNjkxLDg0LjE3MjEzMTEgQzE5Ni41MjUwMDcsODEuNDM1MjQ1OSAx
      OTguNzU5NTI2LDc5LjEyMTMxMTUgMjAxLjU1ODc1NCw3Ny41MDA4MTk3IEMyMDQuMzYwNjg0LDc1
      Ljg4MDMyNzkgMjA3LjYxMTEzOSw3NS4wMTk2NzIxIDIxMC45MjkxNDMsNzUuMDI0NTkwMiBMMjI4
      LjExMzU5Myw3NS4wMjQ1OTAyIEwyNDgsMjI1IFoiIGlkPSJwYXRoMTAyOCIgZmlsbD0iIzREMjFB
      RSIgZmlsbC1ydWxlPSJub256ZXJvIj48L3BhdGg+CiAgICA8L2c+Cjwvc3ZnPg==
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - policy-as-code
  links:
  - name: Mondoo
    url: https://mondoo.com
  maintainers:
  - email: hello@mondoo.com
    name: Mondoo
  maturity: alpha
  provider:
    name: Mondoo, Inc
  version: 0.0.0
