apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: mondoo-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MondooClient is the Schema for the mondooclients API
      displayName: Mondoo Client
      kind: MondooClient
      name: mondooclients.k8s.mondoo.com
      version: v1alpha1
  description: A Kubernetes Operator for creating and managing Mondoo controller instances.
  displayName: mondoo-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - policy-as-code
  links:
  - name: Mondoo Operator
    url: https://mondoo-operator.domain
  maturity: alpha
  provider:
    name: Mondoo, Inc
    url: 'Website: mondoo.com'
  version: 0.0.0
