apiVersion: k8s.mondoo.com/v1alpha1
kind: MondooAuditConfig
metadata:
  name: mondoo-client
  namespace: mondoo-operator
spec:
  workloads:
    enable: false
  nodes:
    enable: false
  webhooks:
    enable: true
    image:
      tag: latest
    certificateConfig:
      injectionStyle: cert-manager # <--- remember to install cert-manager first
  mondooSecretRef: mondoo-client
  
