apiVersion: k8s.mondoo.com/v1alpha1
kind: MondooClient
metadata:
  name: mondoo-client
  namespace: mondoo-operator-system
data:
  workloads:
    enable: true
    workloadserviceaccount: mondoo-operator-workload
  nodes:
    enable: true
  mondoosecretref: mondoo-client
  
