apiVersion: k8s.mondoo.com/v1alpha2
kind: MondooAuditConfig
metadata:
  name: mondoo-client
  namespace: mondoo-operator
spec:
  mondooTokenSecretRef:
    name: mondoo-token
  mondooCredsSecretRef: 
    name: mondoo-client
  scanner:
    serviceAccountName: mondoo-client
    image:
      name: docker.io/mondoo/client
      tag: latest
    resources:
      requests:
      limits:
  kubernetesResources:
    enable: true
  nodes:
    enable: true
  admission:
    enable: true
    certificateProvisioning:
    # Could be "cert-manager", "openshift" or "manual"
      mode: cert-manager
    image:
      name: ghcr.io/mondoo/mondoo-operator
      tag: latest
    # could be "permissive" or "enforcing"
    mode: permissive
  filtering:
    namespaces:
      include:
        - default
        - my-work*
        - mondoo-operator
      # Specifying both include and exclude results in the exclude
      # list being ignored, as the include list is effectively the
      # same as exclude ALL except for the include list.
      exclude:
        - kube-system
