apiVersion: k8s.mondoo.com/v1alpha1
kind: MondooClient
metadata:
  name: mondoo-client
  namespace: mondoo-operator-system
data:
  kubeapi:
    enable: true
  kubenodes:
    enable: true
  mondoosecretref: mondoo-client
