apiVersion: k8s.mondoo.com/v1alpha1
kind: MondooAuditConfig
metadata:
  name: mondoo-client
  namespace: mondoo-operator
spec:
  workloads:
    enable: true
    serviceAccount: mondoo-operator-workload
    tag: latest
  nodes:
    enable: true
    tag: latest
  mondooSecretRef: mondoo-client
  
