apiVersion: k8s.mondoo.com/v1alpha1
kind: MondooAuditConfig
metadata:
  name: mondoo-client
  namespace: mondoo-operator
spec:
  workloads:
    enable: true
    serviceAccount: mondoo-operator-workload
    image:
      name: docker.io/mondoolabs/mondoo
      tag: latest
  nodes:
    enable: true
    image:
      name: docker.io/mondoolabs/mondoo
      tag: latest
  mondooSecretRef: mondoo-client
  
