apiVersion: k8s.mondoo.com/v1alpha2
kind: MondooAuditConfig
metadata:
  name: mondoo-client
  namespace: mondoo-operator
spec:
  mondooCredsSecretRef:
    name: mondoo-client
  kubernetesResources:
    enable: true
  containers:
    enable: true
  nodes:
    enable: false
  admission:
    enable: false
    certificateProvisioning:
      # Could be "cert-manager", "openshift" or "manual"
      mode: cert-manager
  