# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

- op: add
  path: "/spec/description"
  value: |
    The **Mondoo Operator** provides a new [Kubernetes](https://kubernetes.io/) native way to do a security assessment of your whole Kubernetes Cluster. The purpose of this project is to simplify and automate the configuration for a Mondoo-based security assessment for Kubernetes clusters.

    The Mondoo Operator provides the following features:

    - Continuous validation of deployed workloads
    - Continuous validation of Kubernetes nodes **without** privileged access
    - Admission Controller

    It is backed by Mondoo's powerful policy-as-code engine [cnspec](https://mondoo.com/docs/cnspec/cnspec-about/) and [MQL](https://mondoo.com/docs/mql/resources/). Mondoo ships out-of-the-box security policies for:

    - CIS Kubernetes Benchmarks
    - CIS AKS/EKS/GKE/OpenShift Benchmarks
    - NSA/CISA Kubernetes Hardening Guide
    - Kubernetes Cluster and Workload Security
    - Kubernetes Best Practices

    Further information is available at [User manual](https://github.com/mondoohq/mondoo-operator/blob/main/docs/user-manual.md).

    1. Install the operator

    2. Configure the Mondoo Secret

    - Create a new Mondoo service account to report assessments to [Mondoo Platform](https://mondoo.com/docs/platform/maintain/access/service_accounts/)
    - Store the service account json into a local file `creds.json`
    - Store service account as a secret in the mondoo namespace via:

    ```bash
    kubectl create secret generic mondoo-client --namespace mondoo-operator --from-file=config=creds.json
    ```

    3. Create `mondoo-config.yaml`

    ```yaml
    apiVersion: k8s.mondoo.com/v1alpha2
    kind: MondooAuditConfig
    metadata:
      name: mondoo-client
      namespace: mondoo-operator
    spec:
      kubernetesResources:
        enable: true
      nodes:
        enable: true
    ```

    Apply the configuration via:

    ```bash
    kubectl apply -f mondoo-config.yaml
    ```

    4. You can see the results in the [dashboard](https://console.mondoo.com)
