name: Publish cnspec container with providers

on:
  repository_dispatch:
    types: [update]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the cnspec container to publish'
        type: string
        required: false
        default: 'latest'

env:
  IMAGE: ghcr.io/mondoohq/mondoo-operator/cnspec

jobs:
  build-cnspec:
    name: Build cnspec container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        suffix:
          - ""
          - -rootless
          - -ubi-rootless
          - -ubi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sanitize version input
        run: |
          TAG=${{ github.event.inputs.version }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=semver,pattern={{version}},value=${{ env.VERSION }}
            type=semver,pattern={{major}},value=${{ env.VERSION }}
            type=raw,value=latest
          flavor: |
            suffix=${{ matrix.suffix }},onlatest=true

      - name: Build and push cnspec image
        id: build-and-push-operator
        uses: docker/build-push-action@v5
        with:
          context: .
          file: cnspec.Dockerfile
          build-args: VERSION=${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}