name: Publish cnspec container with providers

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the cnspec container to publish'
        type: string
        required: false
        default: 'latest'

env:
  IMAGE: ghcr.io/mondoohq/mondoo-operator/cnspec

jobs:
  build-cnspec:
    name: Build cnspec container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        os: [linux]
        tag:
          - ${{ github.event.inputs.version }}
          - ${{ github.event.inputs.version }}-rootless
          - ${{ github.event.inputs.version }}-ubi-rootless
          - ${{ github.event.inputs.version }}-ubi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push cnspec image
        id: build-and-push-operator
        uses: docker/build-push-action@v4
        with:
          context: .
          file: cnspec.Dockerfile
          build-args: VERSION=${{ github.event.inputs.version }}
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ env.IMAGE }}:${{ matrix.tag }}