name: Edge integration tests
on:
  workflow_dispatch:
    inputs:
      mondooClientImageTag:
        description: "The Mondoo client image tag to be used for the integration tests"
        required: true
        type: string

jobs:
  integration-tests:
    uses: ./.github/workflows/integration-tests.yaml
    with:
      mondooClientImageTag: ${{ github.event.inputs.mondooClientImageTag }}
      useEdge: true
    secrets: inherit
    