name: Edge integration tests
on:
  workflow_dispatch:
    inputs:
      cnspecImageTag:
        description: "The cnspec image tag to be used for the integration tests"
        required: true
        type: string

jobs:
  integration-tests:
    uses: ./.github/workflows/integration-tests.yaml
    with:
      cnspecImageTag: ${{ github.event.inputs.cnspecImageTag }}
    secrets: inherit
    