
name: generate-manifests
on:
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: generate manifests
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - run: make deploy-yml