name: generate-manifests
on:
  push:
    branches:
      - "main"
    tags: ["v*.*.*"]
jobs:
  generate-manifests:
    runs-on: ubuntu-latest
    name: Generate manifests
    steps:
      - uses: actions/checkout@v2
      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "${{ env.golang-version }}"
      - name: Generate manifests 
        run: make generate-manifests
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: mondoo-operator-manifests.yaml
