name: Integration Tests
on:
  pull_request:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - "main"
    tags: ["v*.*.*"]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    name: Integration tests
    steps:
      - uses: actions/checkout@v2
      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV
      - name: Start minikube
        uses: medyagh/setup-minikube@master
        with:
          memory: 4000m
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.golang-version }}"
      - run: make test/integration/ci
      - uses: actions/upload-artifact@v2  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: integration-test-results
          path: integration-tests.xml
      - name: Upload test logs artifact
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-logs
          path: /home/runner/work/mondoo-operator/mondoo-operator/tests/integration/_output/