name: 'Integration Test Report'
on:
  workflow_run:
    workflows: ['Integration Tests']              # runs after Integration Tests workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: integration-test-results
        name: Report integration test results
        path: '*.xml'                     # Path to test results (inside artifact .zip)
        reporter: java-junit              # Format of test results