name: Integration tests
on:
  workflow_call:
    inputs:
      mondooClientImageTag:
        required: true
        type: string
    secrets:
      MONDOO_CLIENT:
        required: true

env:
  MONDOO_CLIENT_IMAGE_TAG: ${{ github.event.inputs.mondooClientImageTag }}


jobs:
  integration-tests:
    runs-on: ubuntu-latest
    name: Integration tests
    
    strategy:
      matrix:
        # k8s-version: [v1.22.12, v1.23.9, v1.24.3]
        # k8s-distro: [minikube,k3s]
        k8s-version: [v1.24.3]
        k8s-distro: [k3s]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch is nneded for "git tag --list" in the Makefile
      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV

      - name: Start minikube
        uses: medyagh/setup-minikube@master
        if: matrix.k8s-distro == 'minikube'
        with:
          memory: 4000m
          kubernetes-version: ${{ matrix.k8s-version }}

      - name: Start k3s
        uses: nolar/setup-k3d-k3s@v1
        if: matrix.k8s-distro == 'k3s'
        with:
          version: ${{ matrix.k8s-version }}

      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.golang-version }}"

      # Makes it easier to see what was the input for this workflow in case we need to debug.
      - name: Print workflow inputs
        run: echo "${{ toJSON(github.event.inputs) }}"

      - name: Store creds
        run: |
          echo ${{ secrets.MONDOO_CLIENT }} | base64 -d > creds.json

      # Now that dependencies are cached the tests start almost immediately after minikube has started
      # this makes tests fail occasionally. This sleep gives the runner some time to become more stable
      # before the test execution starts.
      - name: Wait a bit for the runner to become more stable
        run: kubectl -n kube-system wait --for=condition=Ready pods --all --timeout=90s

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: imilchev

      - name: Run integration tests
        run: K8S_DISTRO=${{ matrix.k8s-distro }} make test/integration/ci

      - run: mv integration-tests.xml integration-tests-${{ matrix.k8s-version }}.xml
        if: success() || failure()

      - uses: actions/upload-artifact@v3  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:                             # upload a combined archive with unit and integration test results
          name: test-results
          path: integration-tests-${{ matrix.k8s-version }}.xml

      - name: Upload test logs artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-logs-${{ matrix.k8s-version }}
          path: /home/runner/work/mondoo-operator/mondoo-operator/tests/integration/_output/