name: Lint
on:
  pull_request:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - "main"
    tags: ["v*.*.*"]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v3
      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV
      - name: Install Protoc
        run: |
          sudo apt install -y gcc
          make prep/ci/protoc
          echo "${{ github.workspace }}/tools/bin" >> $GITHUB_PATH
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.golang-version }}"
      - run: make generate
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49
          args: --timeout=5m0s
