name: Lint
on:
  pull_request:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - "main"
    tags: ["v*.*.*"]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v3
      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV
      - uses: actions/setup-go@v4
        with:
          go-version: "${{ env.golang-version }}"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49
          args: --timeout=15m0s
