name: Release Helm Chart

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "${{ env.golang-version }}"

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Try the cluster !
        run: kubectl get pods -A

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: "v3.8.0" # default is latest stable
        id: install

      - name: Create and Install Helm chart
        run: |
          trap 'echo "Saving Helm logs" ; kubectl get pods --namespace mondoo-operator -o yaml >> helm-logs.txt ; kubectl logs --namespace mondoo-operator deployment/mondoo-operator-controller-manager >> helm-logs.txt' EXIT
          kubectl create namespace mondoo-operator
          helm install mondoo-operator charts/mondoo-operator --namespace mondoo-operator
          echo ${{ secrets.MONDOO_CLIENT }} > creds.json
          kubectl create secret generic mondoo-client --namespace mondoo-operator --from-file=config=creds.json
          rm creds.json
          kubectl apply -f config/samples/k8s_v1alpha1_mondooauditconfig.yaml
      - name: Verify Mondoo Operator Helm Chart
        run: |
          trap 'echo "Saving Helm logs" ; kubectl get pods --namespace mondoo-operator -o yaml >> helm-logs.txt' EXIT
          kubectl wait --for=condition=Ready pod -l control-plane=controller-manager --namespace mondoo-operator 
          kubectl wait --for=condition=Ready pod -l mondoo_cr=mondoo-client --namespace mondoo-operator --timeout=600s
          curl -sSL http://mondoo.io/download.sh | bash
          mv mondoo /usr/local/bin/ 
          make test/deployment
          kubectl delete -f config/samples/k8s_v1alpha1_mondooauditconfig.yaml
          helm uninstall mondoo-operator  --namespace mondoo-operator
      - name: Run chart-releaser
        # switch back to helm/chart-releaser-action when #60 is fixed
        # https://github.com/helm/chart-releaser-action/issues/60
        uses: luisico/chart-releaser-action@on-tags
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Upload helm logs artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: helm-logs
          path: /home/runner/work/mondoo-operator/mondoo-operator/helm-logs.txt
