---
name: Spell Checking

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  spelling:
    name: Run spell check
    runs-on: ubuntu-latest
    steps:
      - name: checkout-merge
        if: "contains(github.event_name, 'pull_request')"
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{github.event.pull_request.number}}/merge
      - name: checkout
        if: ${{ github.event_name == 'push' ||
          (
          contains(github.event.comment.body, '@check-spelling-bot apply')
          ) }}
        uses: actions/checkout@v2
      - uses: check-spelling/check-spelling@v0.0.19
        id: spelling
        with:
          post_comment: 0
          extra_dictionaries:
            cspell:aws/aws.txt
            cspell:filetypes/filetypes.txt
            cspell:software-terms/softwareTerms.txt
