name: Run Test
on:
  pull_request:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - "main"
    tags: ["v*.*.*"]

# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions:
  contents: read

jobs:
  unit-tests:
    if: |
      !github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/unit-tests.yaml
    name: Unit tests
  security-tests:
    name: Security tests
    needs: [unit-tests]
    if: needs.unit-tests.result == 'success'
    uses: ./.github/workflows/security-tests.yaml
    secrets: inherit
  integration-tests:
    name: Integration tests
    needs: [unit-tests]
    if: needs.unit-tests.result == 'success'
    uses: ./.github/workflows/integration-tests.yaml
    with:
      cnspecImageTag: ""
    secrets: inherit