name: Tests
on:
  pull_request:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - "main"
    tags: ["v*.*.*"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - uses: actions/checkout@v3
      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.golang-version }}"
      
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - run: make test/ci
      - uses: actions/upload-artifact@v3  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: unit-tests.xml
  security-tests:
    needs: [unit-tests]
    runs-on: ubuntu-latest
    name: Security tests
    env:
      # Use docker.io for Docker Hub if empty
      REGISTRY: ghcr.io
      # github.repository as <account>/<repo>
      IMAGE_NAME: ${{ github.repository }}
      RELEASE: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV
      - name: Scan AWS terraform with Mondoo
        uses: mondoohq/actions/terraform@main
        with:
          service-account-credentials: ${{ secrets.MONDOO_CLIENT }}
          path: ".github/terraform/aws/main.tf"
      - name: Scan Azure terraform with Mondoo
        uses: mondoohq/actions/terraform@main
        with:
          service-account-credentials: ${{ secrets.MONDOO_CLIENT }}
          path: ".github/terraform/aks/main.tf"
      - name: Generate manifests
        run: make generate-manifests IMG='${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE }}'
      - name: Scan Kubernetes Manifest with Mondoo
        uses: mondoohq/actions/k8s-manifest@main
        with:
          service-account-credentials: ${{ secrets.MONDOO_CLIENT }}
          path: "mondoo-operator-manifests.yaml"
  integration-tests:
    needs: [unit-tests]
    uses: ./.github/workflows/integration-tests.yaml
    if: needs.unit-tests.result == 'success' # run only if unit-tests are successful
    name: Integration tests
    with:
      mondooClientImageTag: ""
    secrets: inherit
   