name: Unit Tests
on:
  pull_request_target:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - "main"
    tags: ["v*.*.*"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || !github.event.pull_request.head.repo.fork
    name: Unit tests
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.golang-version }}"
      
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - run: make test/ci
      - uses: actions/upload-artifact@v3  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: unit-tests.xml

  security-tests:
    needs: [unit-tests]
    uses: ./.github/workflows/security-tests.yaml
    if: needs.unit-tests.result == 'success' # run only if unit-tests are successful
    name: Security tests
    secrets: inherit
  integration-tests:
    needs: [unit-tests]
    uses: ./.github/workflows/integration-tests.yaml
    if: needs.unit-tests.result == 'success' # run only if unit-tests are successful
    name: Integration tests
    with:
      mondooClientImageTag: ""
    secrets: inherit
   