name: Run Test
on:
  pull_request:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - "main"
    tags: ["v*.*.*"]

# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions:
  contents: read

jobs:
  check-label:
    name: Check label
    runs-on: ubuntu-latest
    if: |
      (!github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]')
      || (github.actor == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'ok to test'))
      || (github.event.pull_request.head.repo.fork && contains(github.event.pull_request.labels.*.name, 'ok to test'))
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: remove labels
        uses: andymckay/labeler@1.0.4
        with:
          remove-labels: "ok to test"
  unit-tests:
    needs: [check-label]
    if: needs.check-label.result == 'success'
    uses: ./.github/workflows/unit-tests.yaml
    name: Unit tests
  security-tests:
    name: Security tests
    needs: [unit-tests]
    if: needs.unit-tests.result == 'success'
    uses: ./.github/workflows/security-tests.yaml
    secrets: inherit
  integration-tests:
    name: Integration tests
    needs: [unit-tests]
    if: needs.unit-tests.result == 'success'
    uses: ./.github/workflows/integration-tests.yaml
    with:
      mondooClientImageTag: ""
    secrets: inherit