name: Unit Tests
on:
  workflow_call:

# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions:
  contents: read
# Attention: These jobs still have access to all the secrets.

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.golang-version }}"
          cache: true

      - name: Install Protoc
        run: |
          sudo apt install -y gcc
          make prep/ci/protoc
          echo "${{ github.workspace }}/tools/bin" >> $GITHUB_PATH
      
      - run: make test/ci
      - uses: actions/upload-artifact@v3  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: unit-tests.xml
   