name: Unit Tests
on:
  pull_request:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - "main"
    tags: ["v*.*.*"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - uses: actions/checkout@v2
      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.golang-version }}"
      - run: make test/ci
      - uses: actions/upload-artifact@v2  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: unit-test-results
          path: unit-tests.xml
