name: Validate Github Actions
on:
  pull_request:
  push:
    branches:
      - "main"
    tags: ["v*.*.*"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Verify Github Actions
    steps:
      - uses: actions/checkout@v2
      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.golang-version }}"
      - run: |
          curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
          export PATH=$PATH:./bin
          make test/github-actions
