name: Validate Github Actions
on:
  pull_request:
  push:
    branches:
      - "main"
    tags: ["v*.*.*"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Verify Github Actions
    steps:
      - uses: actions/checkout@v3
      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.golang-version }}"
      - run: |
          curl -OLs https://github.com/nektos/act/releases/download/v0.2.26/act_Linux_x86_64.tar.gz
          tar xzf act_Linux_x86_64.tar.gz
          mkdir ./bin
          cp act ./bin
          export PATH=$PATH:./bin
          make test/github-actions
